name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.5'

      - name: Build the application
        run: |
          echo "Building application with tag: ${{ github.event.release.tag }}"
          pyinstaller --onefile --windowed --name "RPGMV_Extractor.exe" --icon="icon\simple_app_icon.ico" gui.py

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag }}
          files: ./dist/RPGMV_Extractor.exe 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}